### PR TITLE
Add some info about vcenter and norm params

### PR DESCRIPTION
**Pull request by gokceneraslan**
I added two plots showing how vcenter and norm params (added in https://github.com/theislab/scanpy/pull/1551) are used. There are also a few small fixes like replace `louvain` with `clusters` and fix cluster cell type mapping which was designed for 12 clusters although we have 9 now.

### CODE REVIEW

**Comment by ivirshup** [comment]
What do you think about having a separate document all about how colors are handled in the plotting API? This could start with just the examples you have here for continuous colors. It would also have categorical, and null value handling added, but that would be separate. I'm thinking of something a bit more topical, kind of like this: https://seaborn.pydata.org/tutorial/color_palettes.html

**Comment by gokceneraslan** [comment]
@ivirshup Sounds good, I wanna merge the bugfixes in the plotting tutorial but I moved 4 new plots about vcenter/norm to a new tutorial. Do you mind adding the other coloring tricks you have in mind to the new tutorial and merge it @ivirshup ?

**Comment by ivirshup** [comment]
I'm happy to merge the bug fixes, but what do you think about putting the docs for coloring as part of the main documentation?

That way the plots will stay up to date and will be easier to modify/ add to (since we don't have to recommit the entire notebook with embedded plots for any change).

**Comment by gokceneraslan** [comment]
Also sounds good. Shall I make a new PR to keep the git tree a little cleaner then? Or just remove the new notebook with a commit?

**Review by ivirshup — APPROVED** [review]
Great!

Feel free to merge whenever. I have some thoughts on how we could do the user guide.

Least setup would probably just be to do it all with rst, but if you'd prefer to write this stuff in notebooks we can set something up, maybe through `jupytext` and `myst-nb`. We can talk a bit about this at the meeting if you're available

**Comment by gokceneraslan** [comment]
I don't have permission to merge, so feel free to merge it whenever.

**Pull request merged**
