### PR TITLE
scanorama.correct_scanpy issue fixed

### PR DESCRIPTION
**Pull request by RaphaelBuzzi**
Somehow the code did not work for me. I think there was an issue with the scanorama.correct_scanpy function.
Now it works for me. Maybe not the best fix, but I am new to scanpy and GitHub...

### CODE REVIEW

**Comment by ivirshup** [comment]
Ah yeah, I believe scanorama updated their API.

@giovp, does this look good to you?

**Comment by giovp** [comment]
looks great yes!
also, there was a request today on scanpy repo to add a method in the integration list of this tutorial:
https://github.com/theislab/scanpy/issues/1574

@RaphaelBuzzi do you mind adding a line in the very last section of the notebooks, where methods for deconvolution are listed, to include this:
- paper: https://www.biorxiv.org/content/10.1101/2020.11.15.378125v1
- code: https://github.com/BayraktarLab/cell2location

that would be much appreciated!

**Comment by vitkl** [comment]
That would be great, thanks!

**Comment by RaphaelBuzzi** [comment]
@giovp: I added the a new line in the last section with links to the paper and code.

**Review by giovp — APPROVED** [review]

**Comment by giovp** [comment]
thank you @RaphaelBuzzi !

**Comment by vitkl** [comment]
Thank you!

**Pull request merged**
