### PR TITLE
spatial tutorial

### PR DESCRIPTION
**Pull request by giovp**
notebooks to show new plotting function to work with spatial data

### CODE REVIEW

**Comment by flying-sheep** [comment]
Since GitHub throws a hissy fit over the file being tOo BiG, here it is rendered:

https://nbviewer.ipython.org/github/giovp/scanpy-tutorials/blob/spatial/analysis-visualization-spatial.ipynb

**Comment by giovp** [comment]
<p>Addressed all comments</p>

**Comment by giovp** [comment]
Thanks a lot for the review Phil, should have taken everything into account.

**Comment by giovp** [comment]
Right, sorry for this 😅

**Comment by flying-sheep** [comment]
haha no problem, I just think that looks a bit cleaner!

**Pull request merged**
