### PR TITLE
Tutorial notebook for Pearson residuals

### PR DESCRIPTION
**Pull request by jlause**
Hey all!

@giovp asked me over at https://github.com/theislab/scanpy/pull/1715 to create a tutorial/demo notebook for the Pearson residual functions that I wrote for scanpy. Here is the first version I prepared.

In the notebooks I am using two different datasets to demonstrate an example workflow based on Pearson residuals. I borrowed some code/structure from the existing pbmc3k-tutorial, and restricted myself to showing the core functionality of Pearson residuals. For everything not directly demonstrated, I added some info on the optional arguments in the end.

Hope this is along the lines of what you expected - if not I'm happy to adjust :)

Looking forward to your feedback!

Jan

### CODE REVIEW

**Comment by giovp** [comment]
hi @jlause ,

sorry again for late reply , I think the current tutorial look really good! I'd like to have someone else review it as well, I'll ask internally for another pair of eyes as well (should be quicker than mine 😅 ). Will keep you posted here!

Giovanni

**Comment by jlause** [comment]
Hey @cartal and @giovp,

thanks for the feedback and formatting help, I just pushed a revised version - let me know what you think, I can do further improvements next week!

Best, Jan.

**Comment by lazappi** [comment]
@jlause I just went through and made a bunch of comments. Sorry if it's a bit overwhelming but most of them are minor things. There are probably some other minor things in the text but not worth making 100 comments for.

Overall I think this is awesome, particularly the explanation of how the method works 🎉! Thanks for taking the time to contribute the function and the documentation.

**Comment by jlause** [comment]
> @jlause I just went through and made a bunch of comments. Sorry if it's a bit overwhelming but most of them are minor things. There are probably some other minor things in the text but not worth making 100 comments for.
> 
> Overall I think this is awesome, particularly the explanation of how the method works :tada:! Thanks for taking the time to contribute the function and the documentation.

Thanks a lot for the feedback @lazappi, that was very helpful! I made another improved revision including your suggestions which I will push in a moment. You also raised some issues that might require a joint decision from the scanpy team @giovp @cartal @lazappi @ivirshup:

- how should tutorial data be loaded (commented-out `wget` code, `scanpy.dataset` function, just instructions. also: cached or not?). I tried to stick to the 3kPBMC example tutorial here, but will happily adapt if you want it changed
- should the plot I made for inspecting the gene selection become a scanpy function, offering a diagnostic plot to the user? Worth adding it to https://github.com/theislab/scanpy/pull/1715 ? Now or in a later release?

Let me know what you think :)

**Comment by jlause** [comment]
PS: I added a brief mention of the wrapper functions (`recipe_pearson_residuals()` and  `normalize_pearson_residuals_pca()`) in both intro and main part

**Comment by giovp** [comment]
@jlause I decided to also put this paper in references https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9

for the rest, it looks good to me, LGTM

**Review by giovp — APPROVED** [review]

**Comment by jlause** [comment]
Thanks for the feedback!

> @jlause I decided to also put this paper in references https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9

Yes that makes sense! I slightly edited the reference section again to have all references in the same format as the references in the scanpy docs (Authors, _Title_, Journal_with_Link).

> 
> > * how should tutorial data be loaded (commented-out wget code, scanpy.dataset function, just instructions. also: cached or not?). I tried to stick to the 3kPBMC example tutorial here, but will happily adapt if you want it changed
> 
> At this point, I think this is fine although although a bit suboptimal. We have a pbmc3k datasets in Scanpy `sc.datasets.pbmc3k()` but you'd like to use both chemistry versions? what about only one? @ivirshup ideas?

I think it would be nice to keep both in. If I'd need to choose, I'd prefer to keep the newer chemistry, because I think people would like to see a new method demonstrated on that. I could also write a loading function similar to the `sc.datasets.pbmc3k()` one if you wanted to. But at the moment, the same logic is used in the `pbmc3k.ipynb` tutorial, so maybe its fine as it is?! I leave that decision to you and can help implementing whichever way you choose

> > * should the plot I made for inspecting the gene selection become a scanpy function, offering a diagnostic plot to the user? Worth adding it to [Normalization and gene selection by analytical Pearson residuals  scanpy#1715](https://github.com/theislab/scanpy/pull/1715) ? Now or in a later release?
> 
> it would be very useful indeed but I think if you are still willing we can postpone it to another PR.

Okay, if you want to I can setup a PR for that next week and then we can see when there is time to merge it :)

**Comment by giovp** [comment]
> Yes that makes sense! I slightly edited the reference section again to have all references in the same format as the references in the scanpy docs (Authors, Title, Journal_with_Link).

thank you!

> I think it would be nice to keep both in. If I'd need to choose, I'd prefer to keep the newer chemistry, because I think people would like to see a new method demonstrated on that. I could also write a loading function similar to the sc.datasets.pbmc3k() one if you wanted to. But at the moment, the same logic is used in the pbmc3k.ipynb tutorial, so maybe its fine as it is?! I leave that decision to you and can help implementing whichever way you choose

makes sense, let's wait as datasets in general needs refactoring and also another host (pbmc3k in hosted by alex somwhere and makes CI fails sometime)

> Okay, if you want to I can setup a PR for that next week and then we can see when there is time to merge it :)

that'd be great, not sure if we can fit it in for this release already but it'd be useful to have

so I assume this is ready to merge then @jlause ?

**Comment by jlause** [comment]
> > Okay, if you want to I can setup a PR for that next week and then we can see when there is time to merge it :)
> 
> that'd be great, not sure if we can fit it in for this release already but it'd be useful to have

okay sounds good!

> so I assume this is ready to merge then @jlause ?

from my side yes! thanks a lot once more :)

**Pull request merged**
